### ISSUE TITLE
Version 8

### ISSUE THREAD

**Issue by Kwpolska** [getnikola/nikola#1718]
See also: [version 8 project](https://github.com/getnikola/nikola/projects/1)
- [x] resolve all “TODO remove in v8”
- [x] remove features that don’t look very useful (maybe do an user survey?)
- [x] clean up theming and extension documentation while we’re at it
- [x] Nuke the Bootstrap 2 theme #1865
- [x] ~~Do Post refactoring #1709~~
- [x] ~~Do CDN refactoring #1676~~
- [x] Do scan_posts refactor #1700 -- Turned out to be compatible
- [x] ~~Do early tasks support #1632~~
- [x] Enable 'extras' markdown extension by default.
- [x] PRETTY_URLS by default for all new sites (#1838)
- [x] Update IPython.nbconvert to nbconvert (Jupyter) #1938
- [x] Make `nikola install_theme` match the `nikola plugin` API (`nikola theme -i` etc)
- [x] categories/sections merge (#2833)
- [x] Get rid of install_theme
- [x] Get rid of post encryption plugin
- [x] Deprecate/remove `also_create_classifications_from_other_languages` for taxonomies #2785 (?)
- [x] Delete magic tags #2761 
- [x] Add magic tags conversion plugin #3068
- [x] Drop annotations support (annotateit.org closed down in March 2017)
- [x] ~~YAML config~~ #2475 — postponed until v8.1
- [x] Extendable metadata extractors #2830 
- [x] Set `nikola plugin` repo to v8
- [x] Set `nikola theme` repo to v8
- [x] theme compatibility?
- [x] merge categories and sections
- [x] simplify atom file structure

**Comment by felixfontein** [comment]
What is the plan regarding brackwards compatibility breaking changes (like #1632)? From when on can they be merged?

**Comment by Kwpolska** [comment]
Whenever we actually decide we’re going to release v8.0.0, which we are currently reluctant to do.

**Comment by felixfontein** [comment]
How about adding #2761 to this list as well? I'd like to remove support for the deprecated (in #2761) tags in v8.

**Comment by Kwpolska** [comment]
v8 RC 1 coming out later today. v8 final ~48 hours after that if there are no issues.

**Comment by Kwpolska** [comment]
Released!
