### ISSUE TITLE
Python 2.7 deprecation task list

### ISSUE THREAD

**Issue by Kwpolska** [getnikola/nikola#2122]
- [x] Have @ralsina switch his virtualenv to Python 3.4 or better
- [x] Add deprecation warning to v7.7.2 (#2121)
- [x] Switch flake8/pep257 checking to Python 3.5
- [x] Switch invariance testing to Python 3.5
- [x] Switch all remaining infrastructure (plugins site auto-build→(server is now Ubuntu 16.04, not blocked)
- [x] Figure out how to get `-py3`-only wheels: _drop `universal` setting from setup.cfg_
- [x] Clean up AUR packages (python-nikola → nikola; python2-nikola → /dev/null)
- [x] Unpin doit version
- [x] ~~[Write post-mortem (in 2017 maybe)](https://www.reddit.com/r/Python/comments/3mobqw/static_blogging_engine_nikola_to_drop_support_for/cvgxa7x?context=3)~~

**Comment by Kwpolska** [comment]
Tried invariance. For now, charts and RSS are untestable, because they are using dicts. We can probably just delete charts from invariance. But RSS feeds are a bigger problem, because we can’t fix that. Maybe we could migrate to `feedgenerator` instead of using PyRSS2Gen, which is ancient?

**Comment by ralsina** [comment]
@Kwpolska I don't understand the comment about charts and RSS?

**Comment by Kwpolska** [comment]
@ralsina It’s our friend, invariance testing.  Charts and RSS feeds (pygal and pyrss2gen, that is) implement some things as **dicts**.  Which have random order when printing on Python 3.  And you can guess how well this works with `diff`.

**Comment by ralsina** [comment]
I am +1 for switching to feedgenerator or whatever. pygal I guess we could disable when  in invariance mode? Just monkeypatch the directive into repeating the source text or something like it.

**Comment by Kwpolska** [comment]
I added charts.txt it to the excluded files list, so pygal’s not a problem.

So, we have to figure out how to work with feedgenerator and use it.

**Comment by masayuko** [comment]
I have already ported to feedgenerator in my private repository. FYI

**Comment by Kwpolska** [comment]
We’d love a pull request then.

**Comment by masayuko** [comment]
There are two caution points for using my feedgenerator-based code so far.
1. It use my custom feedgenerator that contains some bugfixes and some enhancements. https://github.com/masayuko/python-feedgen
2. The code is designed to prevent as little conflict as possible in order to make it easier to merge into the original nikola. So it need a few adjustments for PR.

**Comment by ralsina** [comment]
All in all, this seems done. Agree @kwpolska? If yes, let's close it.

**Comment by Kwpolska** [comment]
Yes, it is all done. Closing.
