### ISSUE TITLE
The big option name cleanup of 2013

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#601]
There are a number of options whose name makes no sense, or go against the conventions of all the others.

So, since v6 is a major version, let's deprecate them! Let's do a list here:
- [x] ANALYTICS
- [x] post_pages (Issue #644)
- [x] SIDEBAR_LINKS (Issue #104)
- [x] DISQUS_FORUM (Issue #606)
- [x] post_compilers

The deprecation will be done in such a way that using the old names will work but produce warnings, if at all possible.
